version: "3.3"
services:
  nginx:
    image: my-nginx
    build: ./requirements/nginx
    container_name: my-nginx
    ports:
      - "443:443"

    restart: unless-stopped
    volumes:
      - wp-volume:/var/www/
    networks:
    - quarante_deux


  mariadb:
    image: my-maria
    build: ./requirements/mariadb
    container_name: my-db
    expose:
      - "3306"
    restart: unless-stopped
    networks:
      - quarante_deux
    volumes:
      - db-volume:/var/db

  wordpress:
    image: my-wp
    build: ./requirements/wordpress
    container_name: my-wp
    depends_on: 
      - mariadb
    environment:
      - RACK_ENV=development
      - SHOW=true
    expose:
      - "9000"
    restart: unless-stopped
    volumes:
      - wp-volume:/var/www/
    networks:
      - quarante_deux

networks:
    quarante_deux:

volumes:
  wp-volume:
    driver: local
    driver_opts:
      type: vfs
      device: /home/tphung/data/www
      o: bind
  db-volume:
    driver: local
    driver_opts:
      type: vfs
      device: /home/tphung/data/db
      o: bind


